date: "2025-01-22"
author: Yuhang Zang
title: 'InternLM-XComposer2.5-Reward: A Simple Yet Effective Multi-Modal Reward Model'
thumbnail: ""
link: https://huggingface.co/papers/2501.12368
summary: 'The paper introduces InternLM-XComposer2.5-Reward (IXC-2.5-Reward), a multi-modal reward model that aligns Large Vision Language Models (LVLMs) with human preferences. It achieves excellent results on various benchmarks and has three key applications: providing a supervisory signal for RL training, selecting the best response for test-time scaling, and filtering noisy samples from training data. All model weights and training recipes are open-sourced for reproducibility and further research....'
opinion: placeholder
tags:
    - ML
