date: "2024-08-23"
author: Qianqian Xie
title: 'Open-FinLLMs: Open Multimodal Large Language Models for Financial Applications'
thumbnail: ""
link: https://huggingface.co/papers/2408.11878
summary: This paper introduces Open-FinLLMs, a series of financial LLMs that improve upon existing models by incorporating financial knowledge and multimodal inputs. FinLLaMA is pre-trained on a large financial corpus and then fine-tuned with financial instructions, while FinLLaVA is trained with image-text instructions to handle complex financial data types. Evaluations show that Open-FinLLMs outperform existing models on various financial tasks and even achieve high Sharpe Ratios in trading simulations...
opinion: placeholder
tags:
    - ML
