date: "2024-01-18"
author: Jonghyun Lee
title: 'Compose and Conquer: Diffusion-Based 3D Depth Aware Composable Image Synthesis'
thumbnail: https://cdn-uploads.huggingface.co/production/uploads/60f1abe7544c2adfd699860c/-yf5DxmvTrVDfbGeLFsZd.png
link: https://huggingface.co/papers/2401.09048
summary: Addressing the limitations of text as a source of accurate layout representation in text-conditional diffusion models, many works incorporate additional signals to condition certain attributes within a generated image. Although successful, previous works do not account for the specific localization of said attributes extended into the three dimensional plane. In this context, we present a conditional diffusion model that integrates control over three-dimensional object placement with disentangle...
opinion: placeholder
tags:
    - Deep Learning
    - Computer Vision
