date: "2024-11-26"
author: Yoel Zimmermann
title: Reflections from the 2024 Large Language Model (LLM) Hackathon for Applications in Materials Science and Chemistry
thumbnail: ""
link: https://huggingface.co/papers/2411.15221
summary: The Large Language Model (LLM) Hackathon for Applications in Materials Science and Chemistry had 34 teams from different locations, and they used LLMs for various tasks like property prediction, design, automation, communication, data management, hypothesis generation, and knowledge extraction. The event showed that LLMs are getting better and can be used for more tasks in materials science and chemistry research....
opinion: placeholder
tags:
    - ML
