date: "2024-10-24"
author: Srishti Gureja
title: 'M-RewardBench: Evaluating Reward Models in Multilingual Settings'
thumbnail: ""
link: https://huggingface.co/papers/2410.15522
summary: This paper studies the performance of reward models (RMs) in different languages. They created a benchmark called M-RewardBench with 2.87k examples in 23 languages. They found that RMs work better in English than in other languages and that the quality of translation affects RM performance. They also found that RMs work better for languages with more data. They released M-RewardBench and their code to help others study RMs in different languages....
opinion: placeholder
tags:
    - ML
