date: "2024-09-12"
author: Praveen K Kanithi
title: 'MEDIC: Towards a Comprehensive Framework for Evaluating LLMs in Clinical Applications'
thumbnail: ""
link: https://huggingface.co/papers/2409.07314
summary: The paper introduces MEDIC, a comprehensive framework for evaluating Large Language Models (LLMs) in clinical applications. MEDIC assesses LLMs across five critical dimensions, including medical reasoning, ethics and bias, data and language understanding, in-context learning, and clinical safety. The framework uses a novel cross-examination framework to quantify LLM performance without requiring reference outputs. The paper applies MEDIC to various medical tasks and demonstrates performance disp...
opinion: placeholder
tags:
    - ML
