date: "2024-08-22"
author: Felermino D. M. Antonio Ali
title: 'Expanding FLORES+ Benchmark for more Low-Resource Settings: Portuguese-Emakhuwa Machine Translation Evaluation'
thumbnail: ""
link: https://huggingface.co/papers/2408.11457
summary: The paper discusses the expansion of the FLORES+ evaluation set to include Emakhuwa, a low-resource language, by translating the dev and devtest sets from Portuguese into Emakhuwa. The paper details the translation process and quality assurance measures used, and presents baseline results from training a Neural Machine Translation system and fine-tuning existing multilingual translation models. The paper also highlights the challenges faced in Emakhuwa, such as spelling inconsistencies, and the ...
opinion: placeholder
tags:
    - ML
