date: "2024-10-10"
author: Eilam Shapira
title: 'GLEE: A Unified Framework and Benchmark for Language-based Economic Environments'
thumbnail: ""
link: https://huggingface.co/papers/2410.05254
summary: The paper introduces a framework and benchmark for studying two-player, language-based games with large language models. It explores questions about the models' rationality, human-like behavior, and the impact of the game's economic characteristics on their behavior. The framework and benchmark can be used to compare models' behavior to humans, evaluate agents' performance, and study the effects of game characteristics....
opinion: placeholder
tags:
    - ML
