date: "2024-12-12"
author: Yuan Liu
title: 'POINTS1.5: Building a Vision-Language Model towards Real World Applications'
thumbnail: ""
link: https://huggingface.co/papers/2412.08443
summary: POINTS1.5 is a new vision-language model that can handle images of any resolution and has bilingual support, making it better than its predecessor and useful for various real-world tasks. It's also trained on less data and ranks well compared to other models....
opinion: placeholder
tags:
    - ML
