date: "2024-02-26"
author: Jake Bruce
title: 'Genie: Generative Interactive Environments'
thumbnail: https://cdn-uploads.huggingface.co/production/uploads/60f1abe7544c2adfd699860c/bCTVh9dCqN6_e7TSeIsr2.qt
link: https://huggingface.co/papers/2402.15391
summary: This paper introduces Genie, a generative interactive environment trained from unlabelled internet videos. It can create virtual worlds described through text, images, and sketches, and allows users to act in the generated environments without any ground-truth action labels or domain-specific requirements....
opinion: placeholder
tags:
    - Unsupervised Learning
    - Deep Learning
    - Natural Language Processing
    - Computer Vision
    - Robotics and Control
