date: "2024-08-26"
author: Chamith Mawela
title: A Web-Based Solution for Federated Learning with LLM-Based Automation
thumbnail: ""
link: https://huggingface.co/papers/2408.13010
summary: This paper proposes a user-friendly web application for federated learning, which simplifies the orchestration of FL tasks and integrates intent-based automation. The application supports the federated averaging algorithm and optimizes FL performance by implementing model compression and scheduling algorithms. It also explores intent-based automation using a fine-tuned language model, which achieves comparable test accuracy to the standard web-based solution while reducing transferred bytes and ...
opinion: placeholder
tags:
    - ML
