date: "2024-10-21"
author: Syed Abdul Gaffar Shakhadri
title: 'SHAKTI: A 2.5 Billion Parameter Small Language Model Optimized for Edge AI and Low-Resource Environments'
thumbnail: ""
link: https://huggingface.co/papers/2410.11331
summary: Shakti is a 2.5 billion parameter language model that is designed to work well on devices with limited resources, like smartphones and wearables. It can understand and process information in many different languages and is good at specific tasks, like in healthcare or customer service. It is fast and uses less energy than other models, making it perfect for AI applications on devices with limited resources....
opinion: placeholder
tags:
    - ML
