date: "2024-05-31"
author: Chaofan Lin
title: 'Parrot: Efficient Serving of LLM-based Applications with Semantic Variable'
thumbnail: https://cdn-thumbnails.huggingface.co/social-thumbnails/papers/2405.19888.png
link: https://huggingface.co/papers/2405.19888
summary: Parrot is a system that improves the performance of LLM-based applications by using Semantic Variables to expose application-level knowledge to public LLM services. This allows for data flow analysis and optimization across multiple LLM requests, resulting in up to an order-of-magnitude improvement for popular and practical use cases....
opinion: placeholder
tags:
    - Natural Language Processing
    - Deep Learning
