author: Jake Bruce
date: '2024-02-26'
link: https://huggingface.co/papers/2402.15391
opinion: placeholder
summary: This paper introduces Genie, a generative interactive environment trained
  from unlabelled internet videos. It can create virtual worlds described through
  text, images, and sketches, and allows users to act in the generated environments
  without any ground-truth action labels or domain-specific requirements....
tags:
- Unsupervised Learning
- Deep Learning
- Natural Language Processing
- Computer Vision
- Robotics and Control
thumbnail: https://github.com/deep-diver/hf-daily-paper-newsletter/blob/main/assets/2402.15391.gif?raw=true
title: 'Genie: Generative Interactive Environments'
translated_paths:
  INT: https://raw.githack.com/deep-diver/hf-daily-paper-newsletter/main/translated-papers/2402.15391/paper.en.html
  KR: https://raw.githack.com/deep-diver/hf-daily-paper-newsletter/main/translated-papers/2402.15391/paper.ko.html
