date: "2025-06-20"
author: Yile Gu
title: 'ConsumerBench: Benchmarking Generative AI Applications on End-User   Devices'
thumbnail: ""
link: https://huggingface.co/papers/2506.17538
summary: The paper proposes ConsumerBench, a benchmarking framework to assess the efficiency and response time of generative AI models on personal devices, focusing on real-world scenarios with multiple applications running simultaneously and providing insights for model developers and system designers....
opinion: placeholder
tags:
    - ML
