date: "2025-09-22"
author: Valentin Lacombe
title: 'Reasoning Core: A Scalable RL Environment for LLM Symbolic Reasoning'
thumbnail: ""
link: https://huggingface.co/papers/2509.18083
summary: A new system called Reasoning Core has been created to help Large Language Models (LLMs) improve their symbolic reasoning skills through a scalable environment for Reinforcement Learning with Verifiable Rewards. This system generates a wide variety of problems in areas like planning, logic, parsing, and reasoning, and its design ensures a constant supply of new challenges for LLMs to overcome....
opinion: placeholder
tags:
    - ML
