date: "2025-04-22"
author: Kun Wang
title: 'A Comprehensive Survey in LLM(-Agent) Full Stack Safety: Data, Training   and Deployment'
thumbnail: ""
link: https://huggingface.co/papers/2504.15585
summary: This paper proposes a new concept called 'full-stack' safety to thoroughly examine safety issues in Large Language Models (LLMs) from data preparation to commercialization. By reviewing over 800 papers, the authors offer a comprehensive perspective, extensive literature support, and unique insights into safety in data generation, alignment techniques, model editing, and LLM-based agent systems....
opinion: placeholder
tags:
    - ML
