date: "2025-06-04"
author: Anastasiia Ivanova
title: 'AmbiK: Dataset of Ambiguous Tasks in Kitchen Environment'
thumbnail: ""
link: https://huggingface.co/papers/2506.04089
summary: The researchers present AmbiK, a dataset of ambiguous instructions for a robot in a kitchen environment, which aims to provide a universal benchmark for comparing various methods of task ambiguity detection. AmbiK, which was created using Large Language Models and validated by humans, contains 1000 pairs of ambiguous and unambiguous tasks, along with their corresponding details, for a total of 2000 tasks....
opinion: placeholder
tags:
    - ML
