date: "2025-09-30"
author: Yida Xue
title: 'OceanGym: A Benchmark Environment for Underwater Embodied Agents'
thumbnail: ""
link: https://huggingface.co/papers/2509.26536
summary: OceanGym is a new testing ground for AI in underwater environments, which is difficult due to poor visibility and strong currents. This platform has eight tasks and uses advanced AI models to help agents understand their surroundings, explore, and complete goals, while also showing there's still much to improve for AI to work well in these challenging conditions....
opinion: placeholder
tags:
    - ML
