date: "2025-10-23"
author: Weijie Zhou
title: 'PhysVLM-AVR: Active Visual Reasoning for Multimodal Large Language   Models in Physical Environments'
thumbnail: ""
link: https://huggingface.co/papers/2510.21111
summary: This study presents a new task called Active Visual Reasoning (AVR) that challenges models to actively explore and interact with their environment, similar to humans. The researchers introduce a simulation benchmark and a large dataset to evaluate and train models for this task, resulting in a state-of-the-art Multimodal Large Language Model (MLLM) that outperforms existing models in various tasks, including embodied reasoning and passive visual reasoning....
opinion: placeholder
tags:
    - ML
