date: "2025-03-26"
author: Yupeng Cao
title: 'FinAudio: A Benchmark for Audio Large Language Models in Financial   Applications'
thumbnail: ""
link: https://huggingface.co/papers/2503.20990
summary: 'The paper presents FinAudio, a benchmark for assessing Audio Large Language Models (AudioLLMs) in financial applications, as there is no existing benchmark for this domain. FinAudio evaluates AudioLLMs'' performance on three tasks: 1) automatic speech recognition for short financial audio, 2) automatic speech recognition for long financial audio, and 3) summarization of long financial audio, using datasets specifically curated for financial audio analysis....'
opinion: placeholder
tags:
    - ML
