date: "2025-01-22"
author: Hongjin Su
title: 'Learn-by-interact: A Data-Centric Framework for Self-Adaptive Agents in Realistic Environments'
thumbnail: ""
link: https://huggingface.co/papers/2501.10893
summary: Learn-by-interact is a framework that helps LLMs adapt to different environments without human assistance. It creates synthetic data from agent-environment interactions, constructs instructions, and improves the performance of LLMs in various tasks by up to 19.5%....
opinion: placeholder
tags:
    - ML
