date: "2025-03-03"
author: Ádám Kovács
title: 'LettuceDetect: A Hallucination Detection Framework for RAG Applications'
thumbnail: ""
link: https://huggingface.co/papers/2502.17125
summary: LettuceDetect is a hallucination detection framework designed for RAG systems that surpasses previous models in performance and efficiency. It uses ModernBERT for extended context capabilities, outperforms encoder-based models, and can process multiple examples per second....
opinion: placeholder
tags:
    - ML
