date: "2025-03-04"
author: Mingcong Lei
title: 'CLEA: Closed-Loop Embodied Agent for Enhancing Task Execution in Dynamic Environments'
thumbnail: ""
link: https://huggingface.co/papers/2503.00729
summary: The Closed-Loop Embodied Agent (CLEA) is a new architecture designed to improve task execution in dynamic environments. It uses four specialized open-source LLMs with functional decoupling, an interactive task planner, and a multimodal execution critic to ensure reliable execution of subtask sequences and achieve one-shot success in long-term task completion. It outperforms a baseline model in real environment tasks with heterogeneous robots, improving success and task completion rates by 67.3% ...
opinion: placeholder
tags:
    - ML
