date: "2025-08-20"
author: Jiabo Ye
title: 'Mobile-Agent-v3: Foundamental Agents for GUI Automation'
thumbnail: ""
link: https://huggingface.co/papers/2508.15144
summary: The authors present GUI-Owl, a GUI agent model that outperforms other open-source models in various tasks, and Mobile-Agent-v3, a general-purpose framework that further enhances performance. GUI-Owl's innovations include a large-scale virtual environment, diverse agent capabilities, and a scalable reinforcement learning framework, all of which contribute to its superior performance in GUI automation....
opinion: placeholder
tags:
    - ML
