date: "2025-02-13"
author: Henry Hengyuan Zhao
title: 'WorldGUI: Dynamic Testing for Comprehensive Desktop GUI Automation'
thumbnail: ""
link: https://huggingface.co/papers/2502.08047
summary: The authors present WorldGUI, a new benchmark for GUI automation tasks with various initial states, and propose GUI-Thinker, a holistic framework for managing the complexity of GUI interactions, which outperforms a prior state-of-the-art model by 14.9% on WorldGUI tasks....
opinion: placeholder
tags:
    - ML
