date: "2025-10-11"
author: Siyuan Lu
title: Don't Just Fine-tune the Agent, Tune the Environment
thumbnail: ""
link: https://huggingface.co/papers/2510.10197
summary: The authors propose a new method called Environment Tuning to train language model agents for complex tasks, which addresses the issues of overfitting and training instability in existing methods. This approach allows agents to learn from problem instances directly and demonstrates better performance and generalization compared to other methods using a smaller amount of data....
opinion: placeholder
tags:
    - ML
