date: "2025-10-11"
author: Jinghao Zhang
title: 'RLFR: Extending Reinforcement Learning for LLMs with Flow Environment'
thumbnail: ""
link: https://huggingface.co/papers/2510.10201
summary: This study proposes RLFR, a new method for improving reasoning abilities in Large Language Models using flow rewards derived from latent space, which is more effective and efficient than previous methods that use auxiliary signals for reward shaping. Experiments on language and multimodal reasoning benchmarks demonstrate the reliability of flow rewards, suggesting a promising paradigm for reward shaping with auxiliary signals....
opinion: placeholder
tags:
    - ML
