date: "2024-06-18"
author: Neelabh Sinha
title: 'Evaluating Open Language Models Across Task Types, Application Domains, and Reasoning Types: An In-Depth Experimental Analysis'
thumbnail: ""
link: https://huggingface.co/papers/2406.11402
summary: This paper analyzes the performance of 10 smaller, open language models across different tasks, domains, and reasoning types. It shows that the best model and prompt style can vary, and that these models can compete with or outperform larger, more advanced models when used correctly....
opinion: placeholder
tags:
    - ML
