date: "2024-10-18"
author: Zichen Zhu
title: 'MobA: A Two-Level Agent System for Efficient Mobile Task Automation'
thumbnail: ""
link: https://huggingface.co/papers/2410.13757
summary: Current mobile assistants are limited by dependence on system APIs or struggle with complex user instructions and diverse interfaces due to restricted comprehension and decision-making abilities. To address these challenges, we propose MobA, a novel Mobile phone Agent powered by multimodal large language models that enhances comprehension and planning capabilities through a sophisticated two-level agent architecture. The high-level Global Agent (GA) is responsible for understanding user commands...
opinion: placeholder
tags:
    - ML
