date: "2025-10-01"
author: Zhangchen Xu
title: 'TOUCAN: Synthesizing 1.5M Tool-Agentic Data from Real-World MCP   Environments'
thumbnail: ""
link: https://huggingface.co/papers/2510.01179
summary: The researchers created Toucan, a large, public dataset with 1.5 million realistic tasks for training language models to use tools. Toucan's tasks are more diverse and complex than existing datasets, and models trained on it perform better on various benchmarks....
opinion: placeholder
tags:
    - ML
