date: "2025-09-23"
author: Mohammed Mehedi Hasan
title: An Empirical Study of Testing Practices in Open Source AI Agent   Frameworks and Agentic Applications
thumbnail: ""
link: https://huggingface.co/papers/2509.19185
summary: The study examines testing practices in open-source AI agent frameworks and applications, identifying ten testing patterns. It reveals that traditional testing methods are widely used to manage uncertainty in AI agents, while novel methods are rarely applied. The study highlights a need for improved support for novel testing methods, adoption of prompt regression testing, and further research into barriers to adoption to build more robust AI agents....
opinion: placeholder
tags:
    - ML
