date: "2025-01-30"
author: Clément Desroches
title: 'Exploring the sustainable scaling of AI dilemma: A projective study of corporations'' AI environmental impacts'
thumbnail: ""
link: https://huggingface.co/papers/2501.14334
summary: This study proposes a methodology to measure the environmental impact of a company's AI portfolio, highlighting that large generative AI models consume significantly more energy than traditional models. Under a high adoption scenario, AI electricity use is projected to rise by a factor of 24.4 by 2030, requiring coordinated efforts across the AI value chain to mitigate its environmental impact....
opinion: placeholder
tags:
    - ML
