date: "2025-09-22"
author: Selva Taş
title: 'Turk-LettuceDetect: A Hallucination Detection Models for Turkish RAG   Applications'
thumbnail: ""
link: https://huggingface.co/papers/2509.17671
summary: The study presents Turk-LettuceDetect, the first set of hallucination detection models tailored for Turkish RAG applications, addressing the issue of generating incorrect information in complex languages like Turkish. The models, based on a Turkish-specific ModernBERT, TurkEmbed4STS, and multilingual EuroBERT, have been trained on a machine-translated dataset and demonstrate high efficiency and precision in detecting hallucinations....
opinion: placeholder
tags:
    - ML
