date: "2025-04-04"
author: Jianhao Zheng
title: 'WildGS-SLAM: Monocular Gaussian Splatting SLAM in Dynamic Environments'
thumbnail: ""
link: https://huggingface.co/papers/2504.03886
summary: WildGS-SLAM is a monocular RGB SLAM system designed for dynamic environments. It uses an uncertainty map to better handle moving objects, improving tracking, mapping, and rendering performance, and is shown to outperform existing methods in various datasets....
opinion: placeholder
tags:
    - ML
