date: "2024-10-16"
author: Chengguang Gan
title: Empirical Study of Mutual Reinforcement Effect and Application in Few-shot Text Classification Tasks via Prompt
thumbnail: ""
link: https://huggingface.co/papers/2410.09745
summary: This paper investigates the Mutual Reinforcement Effect (MRE) in text classification tasks, which suggests that word-level and text-level classifications can mutually enhance each other. The authors demonstrate the existence of MRE through empirical experiments and extend its application to prompt learning, resulting in improved model performance....
opinion: placeholder
tags:
    - ML
