date: "2024-04-16"
author: Hongchi Xia
title: 'Video2Game: Real-time, Interactive, Realistic and Browser-Compatible Environment from a Single Video'
thumbnail: https://cdn-thumbnails.huggingface.co/social-thumbnails/papers/2404.09833.png
link: https://huggingface.co/papers/2404.09833
summary: This paper presents Video2Game, a system that automatically creates interactive and realistic game environments from videos of real-world scenes. It uses neural radiance fields, mesh rendering, and physics modeling to create highly-realistic and real-time renderings, and can be used to build interactive games....
opinion: placeholder
tags:
    - Computer Vision
    - Deep Learning
