date: "2025-09-16"
author: Runnan Fang
title: Towards General Agentic Intelligence via Environment Scaling
thumbnail: ""
link: https://huggingface.co/papers/2509.13311
summary: The study presents a scalable framework for creating diverse, simulated environments to enhance general agentic intelligence, specifically function-calling capabilities, in Large Language Models. By fine-tuning agents in two phases, the proposed model, AgentScaler, significantly improves performance on various agentic benchmarks....
opinion: placeholder
tags:
    - ML
