date: "2025-02-26"
author: Jiani Zheng
title: 'VEM: Environment-Free Exploration for Training GUI Agent with Value Environment Model'
thumbnail: ""
link: https://huggingface.co/papers/2502.18906
summary: A new environment-free RL framework is proposed to train GUI agents using a pretrained Value Environment Model (VEM) that estimates state-action values directly from offline data, avoiding compounding errors and enhancing resilience to UI changes. VEM achieves state-of-the-art performance in both offline and online settings, outperforming environment-free baselines and matching environment-based approaches without interaction costs....
opinion: placeholder
tags:
    - ML
