date: "2025-07-14"
author: Mingxian Lin
title: 'EmbRACE-3K: Embodied Reasoning and Action in Complex Environments'
thumbnail: ""
link: https://huggingface.co/papers/2507.10548
summary: The EmbRACE-3K dataset is created to evaluate the performance of vision-language models in embodied settings, which require online interaction and active scene understanding. The dataset, consisting of over 3,000 tasks in diverse environments, helps assess the models' spatial reasoning and long-horizon planning abilities, with the potential for significant performance improvements through fine-tuning....
opinion: placeholder
tags:
    - ML
