date: "2024-12-03"
author: Aditya Narayan Sankaran
title: Towards Cross-Lingual Audio Abuse Detection in Low-Resource Settings with Few-Shot Learning
thumbnail: ""
link: https://huggingface.co/papers/2412.01408
summary: We explore the use of pre-trained audio representations for detecting abusive language in low-resource languages by applying Few Shot Learning (FSL) and Model-Agnostic Meta-Learning (MAML) framework. Our approach integrates these representations within the MAML framework to classify abusive language in 10 languages. We experiment with various shot sizes (50-200) evaluating the impact of limited data on performance. Additionally, a feature visualization study was conducted to better understand mo...
opinion: placeholder
tags:
    - ML
