date: "2024-09-19"
author: Haoran Ye
title: Measuring Human and AI Values based on Generative Psychometrics with Large Language Models
thumbnail: ""
link: https://huggingface.co/papers/2409.12106
summary: This work presents a new method called Generative Psychometrics for Values (GPV) to measure human and AI values using large language models. The method is based on text-revealed selective perceptions and has been shown to be more accurate and reliable than previous methods. The researchers also apply GPV to measure the values of large language models themselves and find that different value systems can predict the safety of these models....
opinion: placeholder
tags:
    - ML
