date: "2024-08-26"
author: Kazi Hasan Ibn Arif
title: 'HiRED: Attention-Guided Token Dropping for Efficient Inference of High-Resolution Vision-Language Models in Resource-Constrained Environments'
thumbnail: ""
link: https://huggingface.co/papers/2408.10945
summary: HiRED is a token-dropping scheme for high-resolution Vision-Language Models that operates within a fixed token budget before the Large Language Model (LLM) stage. It uses attention in the vision encoder to assess visual content and allocate the token budget, then selects the most important visual tokens from each partition within the budget, dropping the rest. HiRED increases token generation throughput, reduces latency, and saves GPU memory for a single inference....
opinion: placeholder
tags:
    - ML
