date: "2025-10-28"
author: Bo Liu
title: 'SPICE: Self-Play In Corpus Environments Improves Reasoning'
thumbnail: ""
link: https://huggingface.co/papers/2510.24684
summary: The study presents SPICE, a self-improving system that uses a single model to create challenging reasoning tasks and solve them, leading to consistent gains in mathematical and general reasoning benchmarks. Document grounding is crucial for SPICE to generate and achieve increasingly difficult goals, enabling sustained improvement....
opinion: placeholder
tags:
    - ML
