date: "2024-09-23"
author: Maria Rigaki
title: 'Hackphyr: A Local Fine-Tuned LLM Agent for Network Security Environments'
thumbnail: ""
link: https://huggingface.co/papers/2409.11276
summary: Hackphyr is a locally fine-tuned Large Language Model (LLM) agent for network security environments. It runs on a single GPU card and performs as well as larger, more expensive models. It was trained with a new cybersecurity dataset and outperforms other models in complex, unseen scenarios. The paper also analyzes the agent's behavior to understand its planning abilities and limitations....
opinion: placeholder
tags:
    - ML
