date: "2025-05-20"
author: Yu Ying Chiu
title: Will AI Tell Lies to Save Sick Children? Litmus-Testing AI Values   Prioritization with AIRiskDilemmas
thumbnail: ""
link: https://huggingface.co/papers/2505.14633
summary: The authors propose LitmusValues, a method to uncover AI model priorities, and AIRiskDilemmas, a collection of scenarios to test these priorities. They demonstrate that seemingly harmless values in AI models can predict both known and unknown risky behaviors....
opinion: placeholder
tags:
    - ML
