date: "2025-04-26"
author: Connor T. Jerzak
title: Selecting Optimal Candidate Profiles in Adversarial Environments Using   Conjoint Analysis and Machine Learning
thumbnail: ""
link: https://huggingface.co/papers/2504.19043
summary: This study uses conjoint analysis and machine learning to determine the best candidate profiles in competitive political environments. They find that considering the opposing party's strategies leads to more realistic and historically accurate election outcomes....
opinion: placeholder
tags:
    - ML
