date: "2025-10-28"
author: Pengcheng Qiu
title: Evolving Diagnostic Agents in a Virtual Clinical Environment
thumbnail: ""
link: https://huggingface.co/papers/2510.24654
summary: The authors propose a framework to train language models as diagnostic agents using reinforcement learning, allowing them to handle multi-step diagnoses and choose exams wisely. They introduce DiagGym, a virtual clinical environment, and DiagBench, a diagnostic benchmark, and demonstrate that their method outperforms other LLMs in various diagnostic tasks....
opinion: placeholder
tags:
    - ML
