date: "2025-01-28"
author: Chuanyang Zheng
title: 'iFormer: Integrating ConvNet and Transformer for Mobile Application'
thumbnail: ""
link: https://huggingface.co/papers/2501.15369
summary: The authors have developed iFormer, a new mobile hybrid vision network that combines the strengths of ConvNeXt and a modified self-attention mechanism for improved accuracy and reduced latency in mobile applications. iFormer outperforms existing lightweight networks, achieving 80.4% Top-1 accuracy on ImageNet-1k with a latency of only 1.10 ms on an iPhone 13, and also shows better performance in downstream tasks....
opinion: placeholder
tags:
    - ML
