date: "2025-05-14"
author: Yuxin Jiang
title: 'EnerVerse-AC: Envisioning Embodied Environments with Action Condition'
thumbnail: ""
link: https://huggingface.co/papers/2505.09723
summary: The authors present a new model, EVAC, which helps in testing and evaluating robots in dynamic environments without the need for physical robots or complex simulations. This model reduces costs and maintains high accuracy in robotic manipulation evaluation by generating realistic, action-conditioned video observations for policy testing....
opinion: placeholder
tags:
    - ML
