date: "2024-04-12"
author: Tianbao Xie
title: 'OSWorld: Benchmarking Multimodal Agents for Open-Ended Tasks in Real Computer Environments'
thumbnail: https://cdn-thumbnails.huggingface.co/social-thumbnails/papers/2404.07972.png
link: https://huggingface.co/papers/2404.07972
summary: This paper introduces OSWorld, a scalable, real computer environment for multimodal agents to assess open-ended computer tasks. It includes a benchmark of 369 computer tasks and demonstrates the deficiencies of current LLM/VLM-based agents in serving as computer assistants. The code, environment, baseline models, and data are available publicly....
opinion: placeholder
tags:
    - Supervised Learning
    - Unsupervised Learning
    - Reinforcement Learning
    - Natural Language Processing
    - Computer Vision
    - Human-Computer Interaction (HCI) and User Interfaces
