date: "2025-10-23"
author: Dian Yu
title: 'Every Question Has Its Own Value: Reinforcement Learning with Explicit   Human Values'
thumbnail: ""
link: https://huggingface.co/papers/2510.20187
summary: The authors present a new method called RLEV that incorporates human-defined value signals into the reward function of LLMs, improving their performance on tasks with different levels of importance. This method outperforms traditional correctness-only baselines and learns to prioritize high-value prompts while being robust to noisy value signals....
opinion: placeholder
tags:
    - ML
