date: "2025-10-13"
author: Zaid Khan
title: 'One Life to Learn: Inferring Symbolic World Models for Stochastic   Environments from Unguided Exploration'
thumbnail: ""
link: https://huggingface.co/papers/2510.12088
summary: The study presents a framework called OneLife that learns and represents the dynamics of a complex, stochastic environment through conditionally-activated programmatic laws within a probabilistic programming framework. The framework outperforms a strong baseline in 16 out of 23 scenarios tested and demonstrates successful planning ability in the Crafter-OO environment....
opinion: placeholder
tags:
    - ML
