date: "2025-06-24"
author: Lixuan He
title: 'Mem4Nav: Boosting Vision-and-Language Navigation in Urban Environments   with a Hierarchical Spatial-Cognition Long-Short Memory System'
thumbnail: ""
link: https://huggingface.co/papers/2506.19433
summary: Mem4Nav is a new system that helps agents navigate large urban environments by combining fine-grained voxel indexing and high-level landmark connectivity, allowing them to remember and use past experiences and observations for better navigation. This system improves task completion, reduces errors, and enhances overall performance in various navigation tasks compared to previous methods....
opinion: placeholder
tags:
    - ML
