date: "2024-10-01"
author: Hyungjoo Chae
title: 'Coffee-Gym: An Environment for Evaluating and Improving Natural Language Feedback on Erroneous Code'
thumbnail: ""
link: https://huggingface.co/papers/2409.19715
summary: Coffee-Gym is a new environment for training models to provide feedback on code editing. It includes a dataset called Coffee with human code edit traces and machine-written feedback, and a reward function called CoffeeEval that measures the helpfulness of feedback. Coffee-Gym helps train better feedback models for code editing and makes them more accurate than existing models. The dataset and the model are available for others to use....
opinion: placeholder
tags:
    - ML
