date: "2025-04-14"
author: Pierre Le Jeune
title: 'RealHarm: A Collection of Real-World Language Model Application Failures'
thumbnail: ""
link: https://huggingface.co/papers/2504.10277
summary: This study presents RealHarm, a dataset of real-world failures in language model applications, focusing on harms, causes, and hazards from the deployer's perspective. The research reveals that reputational damage is the most common organizational harm, and misinformation is the most prevalent hazard category, while also showing a significant gap in the protection offered by current guardrails and content moderation systems....
opinion: placeholder
tags:
    - ML
