date: "2025-08-22"
author: Dawei Gao
title: 'AgentScope 1.0: A Developer-Centric Framework for Building Agentic   Applications'
thumbnail: ""
link: https://huggingface.co/papers/2508.16279
summary: AgentScope 1.0 is a new version of a framework for building agentic applications that focuses on improving tool-based interactions, abstracts foundational components, and provides unified interfaces and extensible modules. It enhances agent behaviors with the ReAct paradigm, offers advanced infrastructure for better human-agent and agent-agent interactions, and includes built-in agents for specific scenarios, along with robust engineering support for developers....
opinion: placeholder
tags:
    - ML
