date: "2025-04-17"
author: Ranjan Sapkota
title: 'RF-DETR Object Detection vs YOLOv12 : A Study of Transformer-based and   CNN-based Architectures for Single-Class and Multi-Class Greenfruit Detection   in Complex Orchard Environments Under Label Ambiguity'
thumbnail: ""
link: https://huggingface.co/papers/2504.13099
summary: This study compares RF-DETR and YOLOv12 models for detecting greenfruits in complex orchard environments with label ambiguity. RF-DETR outperforms in single-class detection, while YOLOv12 is better for fast-response scenarios, with both models having strengths in specific detection contexts....
opinion: placeholder
tags:
    - ML
