date: "2024-06-07"
author: Zhiheng Xi
title: 'AgentGym: Evolving Large Language Model-based Agents across Diverse Environments'
thumbnail: https://cdn-thumbnails.huggingface.co/social-thumbnails/papers/2406.04151.png
link: https://huggingface.co/papers/2406.04151
summary: The paper proposes a new framework called AgentGym that allows large language model-based agents to explore and learn in diverse environments. The paper also introduces a method called AgentEvol that enables these agents to evolve and improve their performance on their own. The results show that the evolved agents can perform as well as the current state-of-the-art models. The paper also releases the AgentGym suite, which includes the platform, dataset, benchmark, checkpoints, and algorithm impl...
opinion: placeholder
tags:
    - Supervised Learning
    - Natural Language Processing
