date: "2024-10-21"
author: Hyungjoo Chae
title: 'Web Agents with World Models: Learning and Leveraging Environment Dynamics in Web Navigation'
thumbnail: ""
link: https://huggingface.co/papers/2410.13232
summary: This study introduces a new type of web agent called a World-model-augmented (WMA) agent, which helps it make better decisions by simulating the outcomes of its actions. The study also proposes a new way to train language models to predict the next observations, which helps the agent make better decisions. The study shows that the WMA agent is more cost- and time-efficient than other tree-search-based agents....
opinion: placeholder
tags:
    - ML
