date: "2024-05-20"
author: Bishwaranjan Bhattacharjee
title: 'INDUS: Effective and Efficient Language Models for Scientific Applications'
thumbnail: https://cdn-thumbnails.huggingface.co/social-thumbnails/papers/2405.10725.png
link: https://huggingface.co/papers/2405.10725
summary: INDUS is a suite of language models tailored for scientific domains, trained using curated scientific corpora and outperforming general-purpose and existing domain-specific models on new and existing tasks....
opinion: placeholder
tags:
    - Natural Language Processing
    - Deep Learning
