name: mov_to_gif

on: 
  # workflow_dispatch
  workflow_run:
    workflows: ["collect_papers"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up dependencies
        working-directory: py
        run : |
          pip install -r requirements-gif.txt

      - name: test moviepy
        run: |
          python py/archive_mov_gif.py \
            --yaml-dir current \
            --gif-output-github-repo deep-diver/hf-daily-paper-newsletter \
            --gif-output-dir assets \
            --speedx 6 \
            --clip-to 15 \
            --resize-factor 0.4

      - name: Commit Changes
        run: |
          git config --global user.name 'Chansung'
          git config --global user.email 'deep.diver.csp@gmail.com'
          git pull
          git add .
          git commit -m "Automated report"
          git push
