date: "2024-11-04"
author: Reuben Luera
title: Survey of User Interface Design and Interaction Techniques in Generative AI Applications
thumbnail: ""
link: https://huggingface.co/papers/2410.22370
summary: Generative AI applications are becoming more impressive, and this survey focuses on user-guided interactions. It presents taxonomies of how humans interact with AI and user interaction patterns for a variety of use cases. The goal is to create a reference for designers and developers, and lower the entry barrier for learning about the design of generative AI applications....
opinion: placeholder
tags:
    - ML
