date: "2025-09-30"
author: Wei He
title: 'VitaBench: Benchmarking LLM Agents with Versatile Interactive Tasks in   Real-world Applications'
thumbnail: ""
link: https://huggingface.co/papers/2509.26490
summary: The authors present VitaBench, a new benchmark for testing LLM agents in realistic scenarios, such as food delivery and travel services. They found that even advanced models struggle with these complex tasks, achieving only a 30% success rate on cross-scenario tasks....
opinion: placeholder
tags:
    - ML
