date: "2025-02-13"
author: Li Hu
title: 'Animate Anyone 2: High-Fidelity Character Image Animation with Environment Affordance'
thumbnail: ""
link: https://huggingface.co/papers/2502.06145
summary: Animate Anyone 2, a method for character image animation, enhances the interaction between characters and their environments. It uses environmental representations as conditional inputs, employs a shape-agnostic mask strategy for character-environment relationship characterization, and introduces a pose modulation strategy for improved handling of diverse motion patterns....
opinion: placeholder
tags:
    - ML
